version: "3.9"
networks:
  api_network:
    ipam:
      config:
        - subnet: 172.50.0.0/16

services:
  api:
    restart: always
    image: ml_api:1.0.0
    container_name: my_api
    networks:
      api_network:
        ipv4_address: 172.50.0.3
    ports:
            - "8080:8080"
  test1:
    restart: always
    image: test1:1.0.0
    container_name: test1_container
    environment:
      - LOG=1
    networks:
      api_network:
        ipv4_address: 172.50.1.10
    volumes:
      - .:/home/data
  test2:
    restart: always
    image: test2:1.0.0
    container_name: test2_container
    environment:
      - LOG=1
    networks:
      api_network:
        ipv4_address: 172.50.0.5
    volumes:
      - .:/home/data
  test3:
    restart: always
    image: test3:1.0.0
    container_name: test3_container
    environment:
      - LOG=1
    networks:
      api_network:
        ipv4_address: 172.50.0.9
    volumes:
      - .:/home/data
volumes:
  my_vol:
    external: true
    